### PR TITLE
Add external cluster type

### PR DESCRIPTION
**Pull request by alexmasi**
The `external` cluster type will assume the cluster already exists. The `external` cluster will not be managed by KNE setup/teardown. The only implemented method is the cluster health check.

ex.

```
cluster:
  kind: External
ingress:
  kind: MetalLB
  spec:
    manifests: ../../manifests/metallb
    ip_count: 100
cni:
  kind: Meshnet
  spec:
    manifests: ../../manifests/meshnet
controllers:
  - kind: IxiaTG
    spec:
      manifests: ../../manifests/controllers/ixiatg
  - kind: SRLinux
    spec:
      manifests: ../../manifests/controllers/srlinux
  - kind: CEOSLab
    spec:
      manifests: ../../manifests/controllers/ceoslab
```

### CODE REVIEW

**Comment by alexmasi** [comment]
```
$ ./kne_cli deploy ../deploy/kne/kind-bridge.yaml
INFO[0000] Reading deployment config: "/home/user/kne/deploy/kne/kind-bridge.yaml"
INFO[0000] Using external cluster
INFO[0000] Deploying cluster...
INFO[0000] Deploy is a no-op for the external cluster type
INFO[0000] Cluster deployed
Kubernetes control plane is running at https://10.128.0.23:6443
CoreDNS is running at https://10.128.0.23:6443/api/v1/namespaces/kube-system/services/kube-dns:dns/proxy

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
INFO[0000] Cluster healthy
INFO[0000] Checking kubectl versions.
INFO[0000] Found k8s versions:
clientVersion:
  buildDate: "2022-10-12T10:57:26Z"
  compiler: gc
  gitCommit: 434bfd82814af038ad94d62ebe59b133fcb50506
  gitTreeState: clean
  gitVersion: v1.25.3
  goVersion: go1.19.2
  major: "1"
  minor: "25"
  platform: linux/amd64
kustomizeVersion: v4.5.7
serverVersion:
  buildDate: "2022-10-12T10:49:09Z"
  compiler: gc
  gitCommit: 434bfd82814af038ad94d62ebe59b133fcb50506
  gitTreeState: clean
  gitVersion: v1.25.3
  goVersion: go1.19.2
  major: "1"
  minor: "25"
  platform: linux/amd64

INFO[0000] Deploying ingress...
...
```

**Comment by alexmasi** [comment]
https://github.com/openconfig/kne/issues/225

**Review by guoshiuan — APPROVED** [review]
This implementation should be sufficient for now by relying the the users to have a running cluster other than kind.

Had offline discussion with Alex, if there is any specific per-exterenal-cluster operations need to be done, e.g., loading the version of image specified in the topology proto (if applicable), we can add fields in this external spec.

**Pull request merged**
