### PR TITLE
Ixia operator upgrade

### PR DESCRIPTION
**Pull request by anjan-keysight**
Ixia operator upgrade

### CODE REVIEW

**Comment by alexmasi** [comment]
can you update the go mod too? https://github.com/openconfig/kne/blob/76748ee46d48fe955b7d654ab772bae22c2bae10/go.mod#L16

**Comment by anjan-keysight** [comment]
Updated go mod and sum

**Comment by alexmasi** [comment]
Can you sign the CLA? Then we can merge this, thanks

**Comment by alexmasi** [comment]
done in https://github.com/openconfig/kne/pull/402

**Pull request closed without merging**
