### PR TITLE
Use ghcr.io for kindnetd

### PR DESCRIPTION
**Pull request by n0shut**
Kindnetd moves from docker registry to ghcr.io

https://github.com/aojea/kindnet/commit/a5cb03e777ba1fad382514f50740f6052181a7ff

### CODE REVIEW

**Review by alexmasi — DISMISSED** [review]

**Comment by alexmasi** [comment]
Thanks for the fix

**Comment by alexmasi** [comment]
Can you merge in the new changes to main into this branch so we can re-run the presub? I think the failure was an unrelated flake but want to be sure

**Comment by n0shut** [comment]
@alexmasi done

**Comment by alexmasi** [comment]
Looks like v1.1.0 is leading to an error: `kube-system          kindnet-2trtk                               0/1     Init:CrashLoopBackOff`

**Review by alexmasi — DISMISSED** [review]

**Pull request merged**
