### PR TITLE
Update Nokia config.

### PR DESCRIPTION
**Pull request by guoshiuan**

### CODE REVIEW

**Comment by alexmasi** [comment]
Please revert all files except for `cloudbuild/vendors/srl.cfg`, @MarcCharlebois will handle the other files after the main branch release includes the breaking config change

**Comment by MarcCharlebois** [comment]
Ack:
- Change ports from Default to IANA assigned in Configs,
- Change the g* protocol ports exposed below https://github.com/openconfig/kne/blob/f197e16f84e47b8eadc4263d71fafe92b28dfbd9/topo/node/nokia/nokia.go#L332
- Configure CPM ACLs to allow IANA assigned ports through. (similar to what's in FP)

**Comment by guoshiuan** [comment]
> Please revert all files except for `cloudbuild/vendors/srl.cfg`, @MarcCharlebois will handle the other files after the main branch release includes the breaking config change

Done.

**Review by alexmasi — APPROVED** [review]

**Pull request merged**
