### PR TITLE
juniper: enable p4rt

### PR DESCRIPTION
**Pull request by nitinsoniism**
Enabling p4rt for ncptx, cptx

### CODE REVIEW

**Comment by alexmasi** [comment]
Does this mean the issues in the p4rt impl have been addressed in the latest release? https://github.com/openconfig/kne/pull/349/files#r1232639599

**Comment by alexmasi** [comment]
can you turn the p4rt tests on for both cptx and ncptx: https://github.com/openconfig/kne/blob/921a83f8580c87dee549e65022ddf00bfb721991/cloudbuild/vendors/vendors_test.go#L76 ?

**Comment by nitinsoniism** [comment]
> Does this mean the issues in the p4rt impl have been addressed in the latest release? https://github.com/openconfig/kne/pull/349/files#r1232639599

We had a decent number of P4RT ONDATRA test passes in the latest. We are testing a few more things. I will get back to you in a couple of days.

**Comment by nitinsoniism** [comment]
Closing this for now. Some P4RT testing is in progress. I will get back to this in a few weeks.

**Pull request closed without merging**
