### PR TITLE
Bump scrapligo version to 1.1.11

### PR DESCRIPTION
**Pull request by xuqma**
To include the [pty leak fix](https://github.com/scrapli/scrapligo/pull/135) for scrapligo in https://github.com/scrapli/scrapligo/releases/tag/v1.1.10.

### CODE REVIEW

**Comment by hellt** [comment]
you can bump to 1.10.11 where a race has been fixed

**Comment by xuqma** [comment]
Updated scrapligo to the latest v1.1.11 to include more fixes as suggested.

**Review by bormanp — APPROVED** [review]

**Pull request merged**
