### PR TITLE
implementing resetter for srlinux

### PR DESCRIPTION
**Pull request by Hobbydos**

### CODE REVIEW

**Comment by hellt** [comment]
if we need tests for that, I can have a look at it

**Comment by alexmasi** [comment]
Yes, a unit test for ResetCfg implementation would be good. Here is an example of a unit test for cEOS implementation: https://github.com/openconfig/kne/blob/737516aac0a5477770eb2b96dd8f4c05de8a793b/topo/node/ceos/ceos_test.go#L303 (which looks like you wrote a good chunk of)

**Review by marcushines — APPROVED** [review]

**Review by marcushines — COMMENTED** [review]
please add a test

**Comment by hellt** [comment]
@marcushines unit tests are added in #187 which should supersede this PR

**Comment by hellt** [comment]
With #187 merfed this can be safely closed

**Pull request closed without merging**
