### PR TITLE
Align kind + k8 versioning

### PR DESCRIPTION
**Pull request by alexmasi**
Use v0.26.6 kindest/node which is compatible with v0.20.0 of kind: https://github.com/kubernetes-sigs/kind/releases/tag/v0.20.0

Pin kind version in provisioner scripts

### CODE REVIEW

**Comment by alexmasi** [comment]
Will move presubmit to v0.20.0 in a follow up PR

**Review by guoshiuan — DISMISSED** [review]

**Comment by alexmasi** [comment]
Having some issues with kind 20. Changing this PR to do the following:

- pin the kind version to 19 in the image provisioner scripts
- use kindest/node 0.26.0 in all deployment configs
- use k8 0.26 in all code dependencies
- use k8 0.27 for the client (kubectl)
- require at least kind 17 in all deployment configs, however 19 is the latest version known to work

This combination is known to work with KNE for all supported vendor images.

**Review by guoshiuan — APPROVED** [review]

**Pull request merged**
